"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Flag, LogOut } from "lucide-react";
import { createClient } from "@/utils/supabase/client";
import { Logo, StatusBadge } from "@/components/ui";

type Appointment = { id: string; patient_id: string; status: "pending" | "confirmed" | "declined"; created_at: string };
type Review = { id: string; rating: number; comment: string; reported: boolean };

export function CabinetDashboard() {
  const [name, setName] = useState(""); const [appointments, setAppointments] = useState<Appointment[]>([]); const [reviews, setReviews] = useState<Review[]>([]); const [message, setMessage] = useState("");
  async function load() { const supabase = createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const { data: cabinet, error } = await supabase.from("cabinets").select("id, name").eq("owner_id", user.id).single(); if (error || !cabinet) { setMessage("Aucun cabinet n’est associé à ce compte."); return; } setName(cabinet.name); const [appointmentResult, reviewResult] = await Promise.all([supabase.from("appointments").select("id, patient_id, status, created_at").eq("cabinet_id", cabinet.id).order("created_at", { ascending: false }), supabase.from("reviews").select("id, rating, comment, reported").eq("cabinet_id", cabinet.id).order("created_at", { ascending: false })]); if (appointmentResult.error || reviewResult.error) setMessage((appointmentResult.error || reviewResult.error)?.message ?? "Erreur de chargement."); else { setAppointments((appointmentResult.data ?? []) as Appointment[]); setReviews((reviewResult.data ?? []) as Review[]); } }
  useEffect(() => { void load(); }, []);
  async function updateAppointment(id: string, status: "confirmed" | "declined") { const { error } = await createClient().from("appointments").update({ status }).eq("id", id); setMessage(error ? error.message : "Rendez-vous mis à jour."); if (!error) void load(); }
  async function reportReview(id: string) { const { error } = await createClient().from("reviews").update({ reported: true }).eq("id", id); setMessage(error ? error.message : "Avis signalé à l’administration."); if (!error) void load(); }
  async function signOut() { await createClient().auth.signOut(); window.location.assign("/login"); }
  return <main className="min-h-screen bg-brand-soft"><header className="bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-4"><Logo /><button onClick={() => void signOut()} className="inline-flex min-h-11 items-center gap-2 font-bold"><LogOut className="h-4 w-4" />Déconnexion</button></div></header><div className="mx-auto max-w-6xl px-4 py-10"><p className="font-bold text-brand-secondary">{name || "Chargement…"}</p><h1 className="mt-1 text-3xl font-bold">Tableau de bord</h1>{message && <p role="status" className="mt-4 rounded-xl bg-white p-3 font-semibold">{message}</p>}<section className="mt-8 rounded-2xl bg-white p-5 shadow-card"><h2 className="text-2xl font-bold">Demandes de rendez-vous</h2><div className="mt-4 overflow-x-auto"><table className="w-full text-left"><thead><tr className="border-b"><th className="p-3">Patient</th><th className="p-3">Date</th><th className="p-3">Statut</th><th className="p-3">Réponse</th></tr></thead><tbody>{appointments.map((appointment) => <tr key={appointment.id} className="border-b border-brand-soft"><td className="p-3 font-semibold">{appointment.patient_id.slice(0, 8)}…</td><td className="p-3">{new Date(appointment.created_at).toLocaleDateString("fr-FR")}</td><td className="p-3"><StatusBadge status={appointment.status} /></td><td className="p-3">{appointment.status === "pending" ? <div className="flex gap-2"><button onClick={() => void updateAppointment(appointment.id, "confirmed")} className="min-h-11 rounded-lg bg-status-confirmed-bg px-3 font-bold text-status-confirmed">Oui</button><button onClick={() => void updateAppointment(appointment.id, "declined")} className="min-h-11 rounded-lg bg-red-50 px-3 font-bold text-status-declined">Non</button></div> : "—"}</td></tr>)}</tbody></table></div></section><section className="mt-8 rounded-2xl bg-white p-5 shadow-card"><h2 className="text-2xl font-bold">Avis reçus</h2><div className="mt-4 space-y-3">{reviews.map((review) => <article key={review.id} className="flex flex-col justify-between gap-3 rounded-xl border border-brand-soft p-4 sm:flex-row"><div><strong>{review.rating}/5</strong><p className="mt-1">{review.comment}</p></div><button onClick={() => void reportReview(review.id)} disabled={review.reported} className="inline-flex min-h-11 items-center gap-2 rounded-lg px-3 font-bold text-brand-secondary hover:bg-brand-soft disabled:opacity-60"><Flag className="h-4 w-4" />{review.reported ? "Signalé" : "Signaler"}</button></article>)}</div></section></div></main>;
}
