export type Status = "pending" | "confirmed" | "declined";
export type Review = { id: number; patient: string; rating: number; comment: string; reported?: boolean };
export type Cabinet = { id: string; name: string; category: "Dentiste" | "Médecin" | "Psychologue"; specialty: string; wilaya: string; address: string; phone: string; rating: number; price: number; description: string; image: string; gallery: string[]; reviews: Review[] };

const clinicPhotos = ["https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1538108149393-fbbd81895907?auto=format&fit=crop&w=1200&q=80", "https://images.unsplash.com/photo-1584982751601-97dcc096659c?auto=format&fit=crop&w=1200&q=80"];
export const cabinets: Cabinet[] = [
 { id: "sourire", name: "Cabinet Dentaire Sourire", category: "Dentiste", specialty: "Chirurgie dentaire", wilaya: "Alger", address: "12 rue Didouche Mourad, Alger", phone: "021 45 67 89", rating: 4.8, price: 3000, description: "Une équipe attentive pour les soins dentaires de toute la famille, dans un cadre calme et moderne.", image: clinicPhotos[0], gallery: clinicPhotos, reviews: [{id:1,patient:"Nadia B.",rating:5,comment:"Très rassurante et ponctuelle."},{id:2,patient:"Karim M.",rating:4,comment:"Cabinet propre, accueil agréable.",reported:true}] },
 { id: "el-amal", name: "Centre Médical El Amal", category: "Médecin", specialty: "Cardiologie", wilaya: "Oran", address: "8 boulevard Front de Mer, Oran", phone: "041 33 20 10", rating: 4.6, price: 2000, description: "Consultations de médecine générale et spécialisée, avec un suivi personnalisé.", image: clinicPhotos[1], gallery: [clinicPhotos[1],clinicPhotos[2]], reviews: [{id:3,patient:"Sofiane A.",rating:5,comment:"Docteur à l'écoute, je recommande."}] },
 { id: "equilibre", name: "Espace Équilibre", category: "Psychologue", specialty: "Psychologie clinique", wilaya: "Constantine", address: "25 avenue Aouati Mustapha, Constantine", phone: "031 62 14 50", rating: 4.9, price: 2500, description: "Un espace confidentiel dédié à l'écoute, au soutien et au bien-être psychologique.", image: clinicPhotos[2], gallery: [clinicPhotos[2],clinicPhotos[0]], reviews: [{id:4,patient:"Lina K.",rating:5,comment:"Un accompagnement bienveillant et professionnel."}] },
 { id: "sante-plus", name: "Cabinet Santé Plus", category: "Médecin", specialty: "Dermatologie", wilaya: "Blida", address: "4 rue de la Liberté, Blida", phone: "025 40 11 22", rating: 4.5, price: 1000, description: "Dermatologie et médecine esthétique avec une approche respectueuse et claire.", image: clinicPhotos[1], gallery: [clinicPhotos[1]], reviews: [{id:5,patient:"Yasmine R.",rating:4,comment:"Très bon suivi."}] }
];
export const wilayas = ["Adrar","Chlef","Laghouat","Oum El Bouaghi","Batna","Béjaïa","Biskra","Béchar","Blida","Bouira","Tamanrasset","Tébessa","Tlemcen","Tiaret","Tizi Ouzou","Alger","Djelfa","Jijel","Sétif","Saïda","Skikda","Sidi Bel Abbès","Annaba","Guelma","Constantine","Médéa","Mostaganem","M'Sila","Mascara","Ouargla","Oran","El Bayadh","Illizi","Bordj Bou Arréridj","Boumerdès","El Tarf","Tindouf","Tissemsilt","El Oued","Khenchela","Souk Ahras","Tipaza","Mila","Aïn Defla","Naâma","Aïn Témouchent","Ghardaïa","Relizane","Timimoun","Bordj Badji Mokhtar","Ouled Djellal","Béni Abbès","In Salah","In Guezzam","Touggourt","Djanet","El M'Ghair","El Meniaa","El Meghaier","Ménéa","Draâ El Mizan","Aflou","Barika","Boussaâda","Ksar Chellala","El Abiodh Sidi Cheikh","Aïn Oussera","Bir El Ater","Sidi Aïssa"];
export const appointments = [{id:1,patient:"Amine B.",phone:"0550 12 34 56",cabinet:"Cabinet Dentaire Sourire",status:"pending" as Status},{id:2,patient:"Sara K.",phone:"0661 45 78 90",cabinet:"Centre Médical El Amal",status:"confirmed" as Status},{id:3,patient:"Mehdi R.",phone:"0770 22 33 44",cabinet:"Espace Équilibre",status:"declined" as Status}];
export const monthlyFlow = [{month:"Sem. 1",accounts:18,appointments:12},{month:"Sem. 2",accounts:28,appointments:19},{month:"Sem. 3",accounts:24,appointments:20},{month:"Sem. 4",accounts:36,appointments:27}];
